import React, { useState } from "react";
import AlphabetShiftingTool from "../components/tools/AlphabetShiftingTool";
import HaeufigkeitsanalyseTool from "../components/tools/HaeufigkeitsanalyseTool";
import useLevelGuard from "../components/LevelGuard";
import WeiterButton from "../components/WeiterButton";

export default function Kryptoanalyse() {
  useLevelGuard("level1Passed");

  const [verschiebeText, setVerschiebeText] = useState("GOXX OC BOQXOD CSXN JOSDBOSCOX OSX QEDOC WSDDOV EW LOCCOBOC GODDOB JE OBVOLOX");
  const [ersetzenText, setErsetzenText] = useState("CWNZY ECOOY YJ WCUGJCH JCOO UYFYU NEQYQ JZETYJOYQ CH FCZEIBYQ RI JNORYU IUA UNZEOJ RI OIU RI ECFYU JNY ECOOY YNU PCCQHCW NU ACJ FIZE GYFWNZLO ACJ NEQY JZETYJOYQ WCJ CFYQ YJ TCQYU LYNUY FNWAYQ MAYQ GYJPQCYZEY ACQNU IUA TCJ BIYQ YNUYU JNUU ACZEOY CWNZY ECO YNU FIZE MEUY FNWAYQ MAYQ GYJPQCYZEY GYQCAY IYFYQWYGOY JNY JM GIO JNY LMUUOY AYUU ANY ENORY HCZEOY JNY GCUR JZEWCYBQNG IUA AIHH MF ACJ KYQGUIYGYU YNUY GCYUJYFWIYHZEYULYOOY RI BWYZEOYU ANY HIYEY TYQO TCQ CIBRIJOYEYU IUA ANY GCYUJYFWIYHZEYU RI PBWIYZLYU CWJ PWMYORWNZE YNU TYNJJYJ LCUNUZEYU HNO QMOYU CIGYU ANZEO CU NEQ KMQIYFYQQCUUOY ACQCU TCQ UNZEOJ JM JYEQ FYHYQLYUJTYQOYJ CIZE BCUA CWNZY YJ UNZEO JM JYEQ CIJJYQGYTMYEUWNZE ACJ LCUNUZEYU KMQ JNZE ENUJCGYU RI EMYQYU MDY MDY NZE TYQAY RI JPCYO LMHHYU CWJ JNY JPCYOYQ ACQIYFYQ UCZEACZEOY BNYW NEQ YNU ACJJ JNY JNZE ACQIYFYQ ECYOOY TIUAYQU HIYJJYU CFYQ NH HMHYUO LCH NEQ CWWYJ GCUR UCOIYQWNZE KMQ CWJ DYAMZE ACJ LCUNUZEYU OCOJCYZEWNZE YNUY IEQ CIJ AYQ TYJOYUOCJZEY RMG ACQCIB JZECIOY IUA ACUU TYNOYQYNWOY JPQCUG CWNZY CIB ANY BIYJJY AYUU YJ BIEQ NEQ AIQZE AYU LMPB ACJJ JNY UNYHCWJ RIKMQ YNU LCUNUZEYU HNO YNUYQ TYJOYUOCJZEY MAYQ GCQ HNO YNUYQ IEQ RIH ACQCIJEYQKMQRNYEYU GYJYEYU ECOOY KMQ UYIGNYQAY FQYUUYUA QCUUOY JNY SIYQBYWAYNU NEH ENUOYQEYQ IUA LCH GWIYZLWNZEYQTYNJY GYQCAY RIQYZEO IH YJ NU YNU GQMJJYJ LCUNUZEYUWMZE IUOYQ AYQ EYZLY JPQNUGYU RI JYEYU NH UCYZEJOYU HMHYUO TCQ CWNZY ENUOYQEYQ MEUY CIZE UIQ ACQIYFYQ UCZERIAYULYU TNY NU CWWYQ TYWO JNY TMEW TNYAYQ EYQCIJLCYHY ACJ LCUNUZEYUWMZE BIYEQOY YNU JOIYZL GYQCAYCIJ TNY YNU OIUUYW IUA BNYW ACUU PWMYORWNZE JOYNW CF JM PWMYORWNZE ACJJ CWNZY UNZEO YNUYU CIGYUFWNZL ACQCU AYULYU LMUUOY CURIECWOYU YEY JNY YNUYU CUJZEYNUYUA JYEQ ONYBYU JZECZEO ENUIUOYQBNYW YUOTYAYQ TCQ AYQ JZECZEO JYEQ ONYB MAYQ JNY BNYW JYEQ WCUGJCH ENUIUOYQ AYUU JNY ECOOY GYUIG RYNO JNZE IHRIJZECIYU IUA JNZE RI BQCGYU TCJ CWJ UCYZEJOYJ GYJZEYEYU TIYQAY RIYQJO KYQJIZEOY JNY ENUCFRIFWNZLYU IUA RI YQLYUUYU TCJ IUOYQ NEQ TCQ CFYQ YJ TCQ RI AIULYW IH NQGYUA YOTCJ RI JYEYU ACUU FYOQCZEOYOY JNY ANY TCYUAY AYJ JZECZEOYJ IUA FYHYQLOY ACJJ JNY KMWW HNO JZEQCYULYU IUA FIYZEYQQYGCWYU TCQYU ENYQ IUA AMQO JCE JNY WCUALCQOYU IUA FNWAYQ CU ECLYU ECYUGYU NH KMQFYNBCWWYU UCEH JNY YNUYU OMPB KMU YNUYH AYQ QYGCWY YJ JOCUA MQCUGYUHCQHYWCAY ACQCIB CFYQ RI NEQYQ GQMJJYU YUOOCYIJZEIUG TCQ YQ WYYQ JNY TMWWOY AYU OMPB UNZEO BCWWYU WCJJYU CIJ BIQZEO DYHCUAYU IUOYQ NEQ RI YQJZEWCGYU IUA YJ GYWCUG NEQ NEU FYNH KMQFYNBCWWYU NU YNUYU AYQ JZEQCYULY RIQIYZLRIJOYWWYU UC ACZEOY JNZE CWNZY UCZE YNUYH JMWZEYU JOIQR TNQA YJ HNQ GCQ UNZEOJ HYEQ CIJHCZEYU ANY OQYPPY ENUIUOYQRIBCWWYU TNY OCPBYQ TYQAYU JNY HNZE CWWY RI ECIJY BNUAYU NZE TIYQAY JMGCQ UNZEO HCW YOTCJ JCGYU TYUU NZE KMH ACZE BNYWY TCJ JYEQ TCEQJZEYNUWNZE JONHHOY ENUCF ENUCF ENUCF TMWWOY AYQ JOIQR AYUU UNYHCWJ YUAYU TNYKNYWY LNWMHYOYQ TYQAY NZE TMEW FNJ DYORO GYBCWWYU JYNU JCGOY JNY WCIO NZE HIJJ NQGYUATM NU AYQ UCYEY AYJ YQAHNOOYWPIULOJ JYNU TMWWYU HCW JYEYU ACJ TCYQYU JYZEJOCIJYUA LNWMHYOYQ GWCIFY NZE AYUU TNY HCU JNYEO ECOOY CWNZY CWWYQECUA AYQGWYNZEYU NU AYQ JZEIWY GYWYQUO IUA MFTMEW YJ LYNUY JYEQ GIOY GYWYGYUEYNO TCQ NEQ TNJJYU RI RYNGYU TYNW YJ UNYHCUAYU GCF AYQ RIEMYQOY JM TCQ YJ AMZE YNUY GIOY IYFIUG DC ACJ NJO IUGYBCYEQ ANY QNZEONGY YUOBYQUIUG CFYQ ACUU BQCGY NZE HNZE TYWZEYU FQYNOYUGQCA MAYQ WCYUGYUGQCA NZE TMEW ECFYU HCG CWNZY ECOOY TYAYQ KMU YNUYH FQYNOYUGQCA UMZE KMU YNUYH WCYUGYUGQCA ANY GYQNUGJOY KMQJOYWWIUG CFYQ JNY BCUA ACJJ YJ EIYFJZEY GQMJJCQONGY TMYQOYQ TCQYU IH JNY CIJRIJPQYZEYU JMBMQO FYGCUU JNY TNYAYQ MF NZE TMEW GYQCAYTYGJ AIQZE ANY YQAY BCWWYU TYQAY TNY LMHNJZE HIJJ YJ JYNU FYN WYIOYU EYQCIJRILMHHYU ANY HNO AYH LMPB UCZE IUOYU EYQIHWCIBYU ANY CUONPCOENYU GWCIFY NZE JNY TCQ ANYJHCW QYZEO BQME ACJJ UNYHCUA RIEMYQOY AYUU ACJ TMQO LWCUG GCUR IUA GCQ UNZEO QNZEONG CFYQ NZE TYQAY JNY BQCGYU HIYJJYU TNY ACJ WCUA EYNJJO FNOOY HYNUY ACHY NJO ANYJ UYIJYYWCUA MAYQ CIJOQCWNYU IUA JNY KYQJIZEOY RI LUNZLJYU TCYEQYUA JNY JPQCZE JOYWWO YIZE KMQ LUNZLJYU TCYEQYUA NEQ AIQZE ANY WIBO BCWWO GWCIFO NEQ ACJ FQCYZEOYO NEQ BYQONG IUA JNY TYQAYU HNZE BIYQ YNU QYZEO AIHHYJ LWYNUYJ HCYAZEYU ECWOYU TYUU NZE JNY BQCGY UYNU ACJ GYEO CIB LYNUYU BCWW KNYWWYNZEO JOYEO YJ NQGYUATM CUGYJZEQNYFYU ENUCF ENUCF ENUCF AC YJ UNZEOJ TYNOYQ RI OIU GCF FYGCUU CWNZY FCWA TNYAYQ RI QYAYU ANUCE TNQA HNZE EYIOY CFYUA JYEQ KYQHNJJYU GWCIFY NZE ANUCE TCQ NEQY LCORY NZE EMBBY HCU AYULO CU NEQY JZEIYJJYW HNWZE RIQ OYYRYNO ANUCE HYNU WNYFWNUG NZE TMWWOY AI TCYQJO ENYQ IUOYU FYN HNQ NZE BIYQZEOY NU AYQ WIBO GNFO YJ LYNUY HCYIJY CFYQ AI LMYUUOYJO KNYWWYNZEO YNUY BWYAYQHCIJ BCUGYU ANY NJO YNUYQ HCIJ JYEQ CYEUWNZE HIJJO AI TNJJYU CFYQ MF TMEW LCORYU BWYAYQHCYIJY BQYJJYU IUA ENYQ TIQAY CWNZY QYZEO JZEWCYBQNG IUA BIEQ BMQO CIB OQCYIHYQNJZEY TYNJY KMQ JNZE ENU RI JCGYU BQYJJYU LCORYU BWYAYQHCYIJY BQYJJYU LCORYU BWYAYQHCYIJY IUA HCUZEHCW BQYJJYU BWYAYQHCYIJY LCORYU AYUU AC JNY TYAYQ ANY YNUY UMZE ANY CUAYQY BQCGY FYCUOTMQOYU LMUUOY JPNYWOY YJ LYNUY QMWWY TNY JNY JNY JOYWWOY JNY HYQLOY ACJJ JNY YNUJZEWNYB IUA BNUG GYQCAY CU RI OQCYIHYU ACJJ JNY HNO ANUCE ECUA NU ECUA JPCRNYQYU GNUG IUA JYEQ YQUJO RI NEQ JCGOY CWJM ANUCE JCG HNQ ANY TCEQEYNO ECJO AI DYHCWJ YNUY BWYAYQHCIJ GYBQYJJYU CWJ JNY PWMYORWNZE FCIR PCQACIR NU YNUYH ECIBYU KMU RTYNGYU IUA AIYQQYU FWCYOOYQU WCUAYOY IUA AYQ BCWW TCQ RI YUAY CWNZY ECOOY JNZE LYNU FNJJZEYU TYEGYOCU IUA JPQCUG JMBMQO CIB ANY BIYJJY JNY FWNZLOY UCZE MFYU AMZE IYFYQ NEQ TCQ CWWYJ AIULYW KMQ NEQ WCG TNYAYQ YNU WCUGYQ GCUG IUA JNY LMUUOY ACJ TYNJJY LCUNUZEYU NEU ENUIUOYQYNWYU JYEYU AC TCQ LYNU CIGYUFWNZL RI KYQWNYQYU TNY AYQ TNUA TCQ CWNZY ENUOYQEYQ IUA LCH GYQCAY RIQYZEO IH YJ JCGYU RI EMYQYU TCYEQYUA YJ IH YNUY YZLY FMG M HYNUY MEQYU HYNU JZEUIQQFCQO TNY JPCYO NJO YJ GYTMQAYU JNY TCQ ANZEO ENUOYQ NEH CWJ JNY CU ANY YZLY LCH CFYQ ACJ LCUNUZEYU TCQ UNZEO HYEQ RI JYEYU IUA JNY JOCUA NU YNUYH WCUGYU UNYAQNGYU JCCW AYQ KMU YNUYQ QYNEY AYZLYUWCHPYU YQWYIZEOYO TIQAY QNUGJ NH JCCW GCF YJ KNYWY OIYQYU CFYQ JNY TCQYU CWWY KYQJPYQQO IUA CWJ CWNZY YQJO CIB AYQ YNUYU ACUU CIB AYQ CUAYQYU JYNOY DYAY OIYQ CIJPQMFNYQO ECOOY GNUG JNY OQCIQNG AIQZE ANY HNOOY IUA BQCGOY JNZE TNY JNY DYHCWJ TNYAYQ ENUCIJLMHHYU JMWWOY PWMYORWNZE JOCUA JNY KMQ YNUYH LWYNUYU AQYNFYNUNGYU ONJZE AYQ GCUR CIJ GWCJ TCQ ACQCIB WCG UNZEOJ CWJ YNU TNURNGYQ GMWAYUYQ JZEWIYJJYW IUA CWNZYJ YQJOYQ GYACULY TCQ YQ HIYJJY RI YNUYQ AYQ OIYQYU NH JCCW PCJJYU CFYQ CZE YUOTYAYQ TCQYU ANY JZEWMYJJYQ RI GQMJJ MAYQ AYQ JZEWIYJJYW TCQ RI LWYNU DYAYUBCWWJ WNYJJ JNZE LYNUY AYQ OIYQYU ACHNO MYBBUYU FYN NEQYH RTYNOYU QIUAGCUG LCH JNY DYAMZE CU YNUYU UNYAQNGYU KMQECUG AYU JNY KMQEYQ UNZEO FYHYQLO ECOOY IUA ENUOYQ NEH FYBCUA JNZE YNUY LWYNUY OIYQ KNYWWYNZEO BIYUBRYEU RMWW EMZE JNY PQMFNYQOY AYU JZEWIYJJYW IUA RI NEQYQ GQMJJYU BQYIAY PCJJOY YQ CWNZY MYBBUYOY ANY OIYQ IUA JCE ACJJ JNY NU YNUYU YUGYU GCUG UNZEO GQMYJJYQ CWJ YNU QCOOYUWMZE BIYEQOY JNY LUNYOY UNYAYQ IUA FWNZLOY AIQZE AYU GCUG NU AYU YUORIYZLYUAJOYU GCQOYU AYU HCU DY GYJYEYU ECO TNY JYEUOY JNY JNZE ACUCZE CIJ AYH AIYJOYQYU JCCW ENUCIJRIGYWCUGYU IUA RTNJZEYU ANYJYU FIUOYU FWIHYUFYYOYU IUA AYU LIYEWYU JPQNUGFQIUUYU EYQIHRIJPCRNYQYU CFYQ JNY FYLCH UNZEO YNUHCW NEQYU LMPB AIQZE ANY OIYQ IUA JYWFJO TYUU HYNU LMPB ENUAIQZEGNUGY ACZEOY ANY CQHY CWNZY ECYOOY YJ JYEQ TYUNG RTYZL MEUY HYNUY JZEIWOYQU CZE NZE TIYUJZEOY NZE LMYUUOY HNZE TNY YNU BYQUQMEQ RIJCHHYUJZENYFYU NZE GWCIFY NZE LMYUUOY YJ TYUU NZE TIYJJOY TNY HCU ACHNO CUBCYUGO AYUU YJ TCQYU DC FNJEYQ JM KNYWY CIJJYQGYTMYEUWNZEY ANUGY GYJZEYEYU ACJJ CWNZY FYQYNOJ GWCIFOY TNQLWNZE IUHMYGWNZE JYN BCJO UNZEOJ YJ JZENYU RTYZLWMJ RI JYNU CU AYQ LWYNUYU OIYQ RI TCQOYU AYJECWF LYEQOY JNY RI AYH ONJZE RIQIYZL IUA EMBBOY ECWF JNY TYQAY YNUYU CUAYQYU JZEWIYJJYW BNUAYU MAYQ CIB DYAYU BCWW YNU FIZE HNO CUWYNOIUGYU TNY HCU JNZE GWYNZE YNUYH BYQUQMEQ RIJCHHYUJZENYFO CFYQ JNY BCUA UIQ YNU BWCYJZEZEYU CIB AYH ONJZE ACJ KMQEYQ FYJONHHO UNZEO AC TCQ JCGOY CWNZY IUA IH JYNUYU ECWJ TCQ YNU PCPNYQRYOOYW GYFIUAYU CIB AYH NU JZEMYUYU GQMJJYU WYOOYQU ANY TMQOY OQNUL HNZE GYAQIZLO TCQYU OQNUL HNZE TCQ WYNZEO GYJCGO CFYQ ANY LWIGY LWYNUY CWNZY ACZEOY UNZEO ACQCU ACJ JMBMQO RI OIU UYNU NZE TYQAY RIYQJO UCZEJYEYU JCGOY JNY MF GNBO ACQCIB JOYEO MAYQ UNZEO AYUU JNY ECOOY HYEQYQY EIYFJZEY LWYNUY GYJZENZEOYU IYFYQ LNUAYQ GYWYJYU ANY JNZE KYQFQCUUO ECOOYU MAYQ KMU TNWAYU ONYQYU GYBQYJJYU TIQAYU MAYQ CUAYQY IUCUGYUYEHY ANUGY YQWYFOYU UIQ TYNW JNY JNZE UNZEO CU ANY YNUBCZEYU QYGYWU YQNUUYQU TMWWOYU ANY NEQY BQYIUAY JNY GYWYEQO ECOOYU RIH FYNJPNYW ACJJ YNU QMOGWIYEYUAYQ BYIYQECLYU YNUYU KYQFQYUUO TYUU HCU NEU RI WCUGY NU AYQ ECUA ECYWO MAYQ ACJJ YJ GYTMYEUWNZE FWIOYO TYUU HCU JNZE HNO YNUYH HYJJYQ JYEQ ONYB NU AYU BNUGYQ JZEUYNAYO IUA JNY ECOOY UNYHCWJ KYQGYJJYU ACJJ TYUU HCU KNYW CIJ YNUYQ BWCJZEY HNO AYQ CIBJZEQNBO GNBO OQNULO YJ YNUYH BCJO HNO JNZEYQEYNO UNZEO FYLMHHO BQIYEYQ MAYQ JPCYOYQ CIB ANYJYQ BWCJZEY JOCUA DYAMZE UNZEO GNBO AYJECWF TCGOY YJ CWNZY KMU NEQ RI LMJOYU IUA TYNW YJ NEQ JYEQ GIO JZEHYZLOY UCYHWNZE UCZE YNUYQ HNJZEIUG KMU LNQJZEOMYQOZEYU KCUNWWYPIAANUG CUCUCJ PIOYUFQCOYU JCEUYFMUFMUJ IUA EYNJJYH OMCJO HNO FIOOYQ TCQ ANY BWCJZEY JYEQ FCWA WYYQ TCJ BIYQ YNU JYWOJCHYJ GYBIYEW JCGOY CWNZY NZE HIJJ HNZE TMEW TNY YNU BYQUQMEQ RIJCHHYUJZENYFYU IUA JM TCQ YJ OCOJCYZEWNZE JNY TCQ DYORO UIQ UMZE ZH EMZE IUA NEQY HNYUY EYWWOY JNZE FYN AYH GYACULYU CIB ACJJ JNY DYORO ANY QNZEONGY GQMYJJY ECOOY IH AIQZE ANY LWYNUY OIYQ NU AYU YUORIYZLYUAYU GCQOYU RI GYEYU RIUCYZEJO DYAMZE TCQOYOY JNY YNU PCCQ HNUIOYU CF MF JNY UNZEO UMZE TYNOYQ JZEQIHPBOY JNY TCQ ACQIYFYQ YOTCJ FYIUQIENGO AYUU YJ LMYUUOY DC JYNU JCGOY JNZE CWNZY ACJJ NZE KMYWWNG CIJGYEY TNY YNUY LYQRY NZE BQCGY HNZE TCJ NZE ACUU TMEW TCYQY IUA JNY KYQJIZEOY JNZE KMQRIJOYWWYU TNY YNUY LYQRYUBWCHHY CIJJNYEO UCZEAYH ANY LYQRY CIJGYFWCJYU TMQAYU NJO AYUU JNY LMUUOY JNZE UNZEO YQNUUYQU JM YOTCJ DYHCWJ GYJYEYU RI ECFYU CWJ JNY UCZE YNUYQ TYNWY JPIYQOY ACJJ UNZEOJ HYEQ GYJZECE FYJZEWMJJ JNY JMBMQO NU AYU GCQOYU RI GYEYU CFYQ CZE CQHY CWNZY CWJ JNY RIQ OIYQ LCH JOYWWOY JNY BYJO ACJJ JNY AYU LWYNUYU GMWAYUYU JZEWIYJJYW KYQGYJJYU ECOOY IUA CWJ JNY RIQIYZL RIH ONJZE LCH JOYWWOY JNY BYJO ACJJ JNY AYU JZEWIYJJYW IUHMYGWNZE YQQYNZEYU LMUUOY JNY JCE NEU GCUR AYIOWNZE AIQZE ACJ GWCJ IUA JNY KYQJIZEOY NEQ FYJOYJ CU YNUYH AYQ ONJZEFYNUY ENUCIBRILWYOOYQU CFYQ YJ TCQ RI GWCOO IUA CWJ JNY KMU AYU KYQJIZEYU GCUR YQJZEMYPBO TCQ JYOROY JNZE ACJ CQHY LWYNUY ANUG ENU IUA TYNUOY LMHH YJ ECO LYNUYU RTYZL JM RI TYNUYU JCGOY CWNZY RI JNZE JYWFJO NU RNYHWNZE JZECQBYH OMU NZE QCOY ANQ JMBMQO ACHNO CIBRIEMYQYU JNY PBWYGOY JNZE JYWFJO JYEQ GIOY QCOJZEWCYGY RI GYFYU TNYTMEW JNY NEUYU JYEQ JYWOYU BMWGOY IUA HCUZEHCW JZECWO JNY JNZE JYWFJO JM JOQYUG CIJ ACJJ NEQ ANY OQCYUYU LCHYU JNY YQNUUYQOY JNZE TNY JNY YNUHCW KYQJIZEO ECOOY JNZE JYWFJO RI MEQBYNGYU TYNW JNY JNZE FYN YNUYQ LQMZLYOPCQONY ANY JNY HNO JNZE JYWFJO JPNYWOY FYHMGYWO ECOOY AYUU ANYJYJ JYWOJCHY LNUA ECOOY GQMJJYU JPCJJ ACQCU JM RI OIU CWJ JYN YJ RTYN PYQJMUYU CFYQ YJ ECO DYORO LYNUYU RTYZL ACZEOY ANY CQHY CWNZY JM RI OIU CWJ JYN NZE RTYN YJ NJO DC LCIH GYUIG KMU HNQ IYFQNG ACJ BIYQ YNUY QYJPYLOCFWY PYQJMU QYNZEOY FCWA BNYW NEQ FWNZL CIB YNU GWCJLCYJOZEYU ACJ IUOYQ AYH ONJZE WCG JNY MYBBUYOY YJ IUA BCUA ACQNU YNUYU JYEQ LWYNUYU LIZEYU CIB AYH ANY TMQOY NJJ HNZE JZEMYU HNO LMQNUOEYU GYJZEQNYFYU JOCUAYU UIU NZE TYQAY NEU YJJYU JCGOY CWNZY IUA TYUU YQ HNZE GQMYJJYQ TYQAYU WCYJJO LCUU NZE AYU JZEWIYJJYW YQQYNZEYU IUA TYUU YQ HNZE LWYNUYQ TYQAYU WCYJJO LCUU NZE IUOYQ AYQ OIYQ AIQZELQNYZEYU NU AYU GCQOYU TYQAY NZE NU DYAYH BCWW LMHHYU IUA YJ NJO HNQ YGCW TCJ GYJZENYEO JNY CJJ YNUYU LWYNUYU FNJJYU IUA JCGOY JNZE CYUGJOWNZE TMENU TMENU NUAYH JNY ANY ECUA IYFYQ AYU LMPB ENYWO ACHNO JNY HYQLOY NU TYWZEY QNZEOIUG JNY TIZEJ IUA JNY TCQ QYZEO IYFYQQCJZEO CWJ JNY NEQY GQMYJJY FYENYWO JNZEYQWNZE GYJZENYEO ANYJ NU AYU HYNJOYU BCYWWYU TYUU HCU LIZEYU NJJO CFYQ CWNZY ECOOY JNZE JZEMU JM ACQCU GYTMYEUO YNU IUGYTMYEUWNZEYJ GYJZEYEYU RI YQTCQOYU ACJJ NEQ ACJ UMQHCWY GCUR WCUGTYNWNG IUA AIHH KMQLCH JM HCZEOY JNY TYNOYQ IUA ECOOY FCWA AYU LIZEYU CIBGYGYJJYU");
  const [klartextZuordnung, setKlartextZuordnung] = useState(Array(26).fill(""));
  const [caesarShift, setCaesarShift] = useState(0);
  const [showCaesarFreq, setShowCaesarFreq] = useState(false);
  const [showSubFreq, setShowSubFreq] = useState(false);

  const klartextAlphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
  const haeufigkeitDeutsch = "ENISRATDHULCGMOBWFKZPVJYXQ".split("");

  const analyseHaeufigkeit = (text) => {
    const freq = {};
    for (let c of text.toUpperCase()) {
      if (/[A-Z]/.test(c)) {
        freq[c] = (freq[c] || 0) + 1;
      }
    }
    return freq;
  };

  const renderHaeufigkeitBalken = (freq, isCaesar = false) => {
    const max = Math.max(...Object.values(freq));
    const haeufigster = Object.entries(freq).sort((a, b) => b[1] - a[1])[0]?.[0] || "?";
    const abstand = (haeufigster.charCodeAt(0) - "E".charCodeAt(0) + 26) % 26;
    const schluessel = String.fromCharCode("A".charCodeAt(0) + abstand);
    return (
      <div className="flex items-start gap-4">
        <div className="flex gap-2 mt-2 text-xs items-end">
          {Object.entries(freq)
            .sort((a, b) => b[1] - a[1])
            .map(([char, count]) => (
              <div key={char} className="text-center">
                <div
                  className="bg-white/20 mx-auto"
                  style={{ height: `${(count / max) * 100}px`, width: "12px" }}
                ></div>
                <div>{char}</div>
              </div>
            ))}
        </div>
        {isCaesar && (
          <div className="text-sm max-w-lg bg-white/10 p-4 rounded">
            Nun erkennst du, dass '<strong><b>{haeufigster}</b></strong>' der häufigste Buchstabe ist. In der Klartext-Sprache ist '<strong><b>E</b></strong>' der häufigste Buchstabe.
            Zwischen beiden Buchstaben gibt es im Alphabet einen Abstand von <strong><b>{abstand}</b></strong>. Dir fällt auf, dass bei der Caesar-Chiffre alle
            Buchstaben gleichmäßig verschoben werden und <strong><b>{abstand}</b></strong> daher die Verschiebezahl sein sollte. Damit ergibt sich für ein '<strong><b>A</b></strong>' im Klartext also ein <strong><b>{schluessel}</b></strong>.
            Damit hast du eine Vermutung für den Schlüssel. Jetzt kannst du überprüfen, ob das mit dem Ergebnis der Brute Force Methode (Durchprobieren aller Möglichkeiten) übereinstimmt.
          </div>
        )}
      </div>
    );
  };

const renderDeutscheHaeufigkeitBalken = () => {
  const deutscheHaeufigkeit = {
    E: 17.40,
    N: 9.78,
    I: 7.55,
    S: 7.27,
    R: 7.00,
    A: 6.51,
    T: 6.15,
    D: 5.08,
    H: 4.76,
    U: 4.35,
    L: 3.44,
    C: 3.06,
    G: 3.01,
    M: 2.53,
    O: 2.51,
    B: 1.89,
    W: 1.89,
    F: 1.66,
    K: 1.21,
    Z: 1.13,
    P: 0.79,
    V: 0.67,
    J: 0.27,
    Y: 0.04,
    X: 0.03,
    Q: 0.02
  };

  const max = Math.max(...Object.values(deutscheHaeufigkeit));

  return (
    <div className="flex gap-2 mt-2 text-xs items-end">
      {Object.entries(deutscheHaeufigkeit).map(([char, freq]) => (
        <div key={char} className="text-center">
          <div
            className="bg-white/20 mx-auto"
            style={{ height: `${(freq / max) * 100}px`, width: "12px" }}
          ></div>
          <div>{char}</div>
        </div>
      ))}
    </div>
  );
};

  const decryptCaesar = (text, shift) => {
    let result = "";
    for (let char of text.toUpperCase()) {
      if (/[A-Z]/.test(char)) {
        let index = (char.charCodeAt(0) - 65 - shift + 26) % 26;
        result += String.fromCharCode(index + 65);
      } else {
        result += char;
      }
    }
    return result;
  };

  const applyErsetzung = (text, zuordnung) => {
    let result = "";
    const mapping = {};
    zuordnung.forEach((klarChar, idx) => {
      const geheimChar = klartextAlphabet[idx];
      if (klarChar) {
        mapping[geheimChar] = klarChar;
      }
    });
    for (let c of text.toUpperCase()) {
      result += mapping[c] || c;
    }
    return result;
  };

  const haeufigkeitsbasiertesAlphabet = () => {
    const freq = analyseHaeufigkeit(ersetzenText);
    const geheimHaeufigkeit = Object.entries(freq).sort((a, b) => b[1] - a[1]).map(([c]) => c);
    const zuordnung = Array(26).fill("");
    geheimHaeufigkeit.forEach((c, i) => {
      if (i < haeufigkeitDeutsch.length) {
        const geheimIndex = klartextAlphabet.indexOf(c);
        if (geheimIndex !== -1) {
          zuordnung[geheimIndex] = haeufigkeitDeutsch[i];
        }
      }
    });
    return zuordnung;
  };

  const updateKlartextBuchstabe = (index, value) => {
    const newZuordnung = [...klartextZuordnung];
    newZuordnung[index] = value.toUpperCase();
    setKlartextZuordnung(newZuordnung);
  };

  const getGeheimAlphabet = (shift) => {
    return klartextAlphabet.map((_, i) => klartextAlphabet[(i + shift) % 26]);
  };

  return (
    <div className="text-style">
      <h1 className="text-2xl font-bold heading-style mb-4">Let's see what we have...</h1>
      <p className="mb-4">
        Du hast dir in Bagdad ein Zimmer gemietet, um über das nachzudenken, was du inzwischen gelernt hast.
        Das Verschiebeverfahren war noch nicht besonders sicher – doch wie sieht es mit dem Ersetzungsverfahren aus?
        Du beschließt, zunächst nochmal einen Blick auf das Caesar-Verfahren zu werfen...
      </p>

      <div className="mb-8">
        <h2 className="text-xl font-bold heading-style mb-2">Kryptoanalyse beim Verschiebeverfahren</h2>
        <p> Du erinnerst dich daran, dass das Caesar-Verfahren nur eine Verschiebung des Alphabets ist und daher nur 26 mögliche Schlüssel existieren.
            Durch Ausprobieren aller Schlüssel solltest du also jede Nachricht entschlüsseln können.
            Probiere nun für die folgende Nachricht alle 26 möglichen Schlüssel durch, um die Chiffre zu knacken:
            </p>
        <AlphabetShiftingTool initialText={verschiebeText} />
        <p>Das Ausprobieren funktioniert problemlos, aber du erkennst, dass es auch einen systematischen Weg gibt, das Caesar-Verfahren zu knacken.
            Dafür zählst du die Häufigkeit der Buchstaben im Geheimtext und bildest die Buchstaben entsprechend der Häufigkeit in der Klartext-Sprache aufeinander ab.
            Wenn du also herausfindest, welche Buchstaben im Geheimtext besonders häufig vorkommen, kannst du versuchen, diese mit den häufigsten Buchstaben in Klartexten zu vergleichen.
          Am häufigsten ist im Deutschen z. B. das „E“, gefolgt von „N“, „I“, „S“ usw. Im Deutschen finden sich die folgenden Buchstabenhäufigkeiten:</p>
          {renderDeutscheHaeufigkeitBalken()}
        <p><br></br>Nun betrachtest du nochmal die verschlüsselte Botschaft:</p>
        <div className="bg-white/10 p-4 rounded text-sm mb-4">
          {verschiebeText}
        </div>
        <button
          onClick={() => setShowCaesarFreq(!showCaesarFreq)}
          className="mb-2 px-4 py-2 border border-white text-white rounded hover:bg-white hover:text-black transition"
        >
          Buchstabenhäufigkeit anzeigen
        </button>
        {showCaesarFreq && renderHaeufigkeitBalken(analyseHaeufigkeit(verschiebeText), true)}
      </div>

      <div className="mb-8">
        <h2 className="text-xl font-bold heading-style mb-2">Kryptoanalyse beim Ersetzungsverfahren</h2>
        <HaeufigkeitsanalyseTool initialText={ersetzenText} />
      </div>

      <div className="mb-8">
        <h2 className="text-xl font-bold heading-style mb-2">Vergleich der Sicherheit</h2>
        <p>
          Du hast herausgefunden: Das Caesar-Verfahren ist leicht durch Brute-Force knackbar – es gibt nur 26 mögliche Schlüssel.
          Beim Ersetzungsverfahren sind es 26! Möglichkeiten – viel zu viele zum Raten.
          Aber auch hier hilft die Häufigkeitsanalyse - aber nur, wenn der Text lang genug ist, um die Häufigkeiten repräsentativ abzuilden.
        </p>
      </div>

      <WeiterButton to="/level2/fachkonzepte" />
    </div>
  );
}
