// Übung: obligatorische Kommas setzen.

import { uebung } from './uebung.js';

// kommas: Index des Wortes, NACH dem ein Komma stehen muss (ab 0 gezählt).
const k = (satz, kommas, erklaerung, schluss) => ({
  typ: 'komma',
  woerter: satz.split(' '),
  kommas,
  erklaerung,
  ...(schluss ? { schluss } : {}),
});

uebung('#uebung', {
  anweisung: 'Setze alle obligatorischen Kommas. Manche Sätze brauchen keines.',
  aufgaben: [
    k('Als die Glocke läutete standen alle auf', [3],
      'Der Nebensatz „Als die Glocke läutete“ steht im Vorfeld und wird abgetrennt. Erkennbar am finiten Verb „läutete“ am Ende.'),
    k('Wir warteten bis der Regen nachließ', [1],
      'Der Nebensatz mit „bis“ wird abgetrennt.'),
    k('Der Hund der neben ihr saß hob den Kopf', [1, 5],
      'Ein eingeschobener Relativsatz braucht zwei Kommas: vorne und hinten.'),
    k('Sie kaufte Brot Käse und Oliven', [2],
      'Aufzählung: Komma zwischen den Gliedern, aber nicht vor „und“.'),
    k('Er setzte sich auf die Bank um in Ruhe zu lesen', [5],
      'Infinitivgruppe mit „um … zu“ – das Komma ist Pflicht.'),
    k('Es regnete stark doch niemand beschwerte sich', [2],
      'Vor „doch“ steht immer ein Komma.'),
    k('Ich weiß nicht ob der Laden noch offen ist', [2],
      'Ein indirekter Fragesatz ist ein Nebensatz und wird abgetrennt.'),
    k('Basel die Stadt am Rheinknie hat drei Landesgrenzen', [0, 4],
      'Eine Apposition wird beidseitig durch Kommas eingeschlossen.'),
    k('Sie freute sich dass alle gekommen waren', [2],
      'Der dass-Satz ist ein Nebensatz.'),
    k('Obwohl er müde war arbeitete er weiter', [3],
      'Konzessivsatz im Vorfeld, Verb „war“ am Ende.'),
    k('Sie ist größer als ihr Bruder', [],
      'Vergleich ohne eigenes Verb – hier steht kein Komma.'),
    k('Das ist einfacher als gedacht', [],
      'Auch hier folgt nach „als“ kein ganzer Satz.'),
    k('Nach dem Essen gingen wir spazieren', [],
      'Ein einfacher Satz ohne Nebensatz und ohne Aufzählung – kein Komma.'),
    k('Er kam nicht weil er krank war sondern weil er keine Lust hatte', [2, 6],
      'Zwei Kommas: eines vor dem ersten Nebensatz, eines vor „sondern“.'),
    k('Wer zuletzt geht macht das Licht aus', [2],
      'Der Relativsatz ohne Bezugswort steht im Vorfeld und wird abgetrennt.'),
    k('Er ging ohne sich zu verabschieden', [1],
      'Infinitivgruppe mit „ohne … zu“ – das Komma ist Pflicht.'),
    k('Liebe Eltern wir laden Sie herzlich ein', [1],
      'Nach der Anrede steht ein Komma.'),
    k('Das Buch das auf dem Tisch liegt gehört mir', [1, 6],
      'Eingeschobener Relativsatz – zwei Kommas.'),
    k('Er fragte wann der Zug ankommt und ob es eine Verbindung gibt', [1],
      'Nur vor dem ersten Nebensatz steht ein Komma. Zwischen zwei gleichrangigen Nebensätzen mit „und“ steht keines.'),
    k('Nachdem alle gegangen waren löschte sie das Licht', [3],
      'Temporalsatz im Vorfeld, Verb „waren“ am Ende.'),
    k('Der Vortrag war kurz aber sehr gut', [3],
      'Vor „aber“ steht immer ein Komma – auch wenn danach kein ganzer Satz folgt.'),
    k('Sie stand auf ging zum Fenster und öffnete es', [2],
      'Eine Aufzählung von Teilsätzen: Komma zwischen den ersten beiden, nicht vor „und“.'),

    {
      anweisung: 'Ist das Komma hier Pflicht oder freiwillig?',
      satz: 'Sie versprach uns zu helfen.',
      frage: 'Braucht die Infinitivgruppe „uns zu helfen“ ein Komma?',
      optionen: ['freiwillig', 'Pflicht', 'verboten'],
      richtig: 'freiwillig',
      erklaerung: 'Keine der drei Pflichtbedingungen liegt vor: kein „um/ohne/statt“, kein hinweisendes Wort, kein Einschub.',
    },
    {
      anweisung: 'Ist das Komma hier Pflicht oder freiwillig?',
      satz: 'Sie ging früher, um den Zug zu erreichen.',
      frage: 'Braucht die Infinitivgruppe ein Komma?',
      optionen: ['Pflicht', 'freiwillig', 'verboten'],
      richtig: 'Pflicht',
      erklaerung: 'Infinitivgruppen mit „um … zu“ werden immer abgetrennt.',
    },
    {
      anweisung: 'Ist das Komma hier Pflicht oder freiwillig?',
      satz: 'Es regnete und wir blieben zu Hause.',
      frage: 'Braucht es vor „und“ ein Komma?',
      optionen: ['freiwillig', 'Pflicht', 'verboten'],
      richtig: 'freiwillig',
      erklaerung: 'Zwischen zwei Hauptsätzen mit „und“ darf ein Komma stehen, muss aber nicht.',
    },
    {
      anweisung: 'Ist das Komma hier Pflicht oder freiwillig?',
      satz: 'Sie kaufte Äpfel und Birnen.',
      frage: 'Braucht es vor „und“ ein Komma?',
      optionen: ['verboten', 'freiwillig', 'Pflicht'],
      richtig: 'verboten',
      erklaerung: 'In einer Aufzählung steht vor „und“ kein Komma.',
    },
    {
      anweisung: 'Ist das Komma hier Pflicht oder freiwillig?',
      satz: 'Es dauerte länger, als wir gedacht hatten.',
      frage: 'Braucht es vor „als“ ein Komma?',
      optionen: ['Pflicht', 'freiwillig', 'verboten'],
      richtig: 'Pflicht',
      erklaerung: 'Hier folgt ein ganzer Teilsatz mit dem Verb „hatten“ am Ende – also ein Nebensatz.',
    },
    {
      anweisung: 'Ist das Komma hier Pflicht oder freiwillig?',
      satz: 'Leise summend räumte sie die Küche auf.',
      frage: 'Braucht die Partizipgruppe ein Komma?',
      optionen: ['freiwillig', 'Pflicht', 'verboten'],
      richtig: 'freiwillig',
      erklaerung: 'Eine vorangestellte Partizipgruppe darf abgetrennt werden, muss aber nicht. Pflicht wäre es nur bei einem Einschub.',
    },
  ],
});
